setup.py
six.intern was only introduced in 1.8.0.
This patch makes it possible to work in a virtualenv
with --system-site-packages despite an ancient six
(as provided by Ubuntu 14.04 for whatever reasons).
=> Explicitly state the required verison of six.

loopy/codegen/instruction.py
When using CInstructions with plain CTarget() as code generation target,
an AttributeError was thrown when evaluating the if clause here.
This commit uses the var_subst_map of the codegen_state instead.
=> [bugfix] The var_subst_map is a member of codegen_state not of the ecm

loopy/auto_test.py, loopy/target/c/codegen/expression.py, loopy/target/opencl.py, test/test_loopy.py
Previously use of a ConstantArg would cause an error in `loopy/target/c/codegen/expression.py:253`.
This fix re-enables ConstantArgs, and adds a simple test to `test/test_loopy.py`
=> Fixes use of lp.ConstantArg on input arrays

loopy/target/c/__init__.py
get_temporary_decl expects the codegen_state.
=> Minor fix for global temporary declarations in C-based targets

loopy/check.py, test/test_loopy.py
aliasing (closes inducer/loopy#69).
=> check_that_temporaries_are_defined_in_subkernels_where_used(): Respect

loopy/codegen/instruction.py
The `join()` function expects its argument to be a list of strings.
=> fixed an issue when trace_assignment_values=True

loopy/symbolic.py
Passing parameters, *args, **kwargs, missing in Mapper Classes. This is a contradiction to pymbolic. Fix.
=> passing parameters in MapperClasses fix. Contraction with pymbolic

loopy/codegen/__init__.py
Previous implementation wouldn't take vector types into account.
=> Extract seen_dtypes from ImplementedDataInfo

loopy/statistics.py
get_simd_group_size sometimes returns None.
=> fix _find_subgroup_size_for_knl warning

loopy/check.py, loopy/codegen/instruction.py, loopy/kernel/__init__.py, loopy/kernel/creation.py, loopy/kernel/tools.py, loopy/preprocess.py, loopy/schedule/__init__.py, loopy/statistics.py, loopy/symbolic.py, loopy/transform/iname.py, loopy/transform/privatize.py
Simple fix to get ~25% speedup in the scheduling stage for the kernel in #178.
```
(loopy-dev) kgk2@koelsch:~/loopy$ echo $LOOPY_NO_CACHE 
1
(loopy-dev) kgk2@koelsch:~/loopy$ git checkout master 
Already on 'master'
Your branch is up to date with 'origin/master'.
(loopy-dev) kgk2@koelsch:~/oopy$ python disjoint_loop_nests.py 
INFO:loopy.schedule:loopy_kernel: schedule: completed (78.36s wall, 1.0x CPU)
(loopy-dev) kgk2@koelsch:~/loopy$ git checkout replace_insn_inames 
Switched to branch 'replace_insn_inames'
(loopy-dev) kgk2@koelsch:~/loopy$ python disjoint_loop_nests.py                                                                                                                                            
INFO:loopy.schedule:loopy_kernel: schedule: completed (60.10s wall, 1.0x CPU) …
```
=> LoopKernel.insn_inames(insn: InstructionBase) -> insn.within_inames

loopy/check.py, loopy/codegen/__init__.py, loopy/target/c/__init__.py, loopy/target/c/codegen/expression.py, loopy/target/cuda.py, loopy/target/opencl.py, loopy/target/python.py, test/test_loopy.py
- Uses exponentiation by squaring for int exponents. (for all base dtypes)
- Exponentiation with negative exponents is undefined behavior, but the result type is always `np.find_common_type`
=> Fixes int-exponent exponentiation for C-like targets

loopy/target/pyopencl.py, requirements.txt
=> Use PyOpenCL 2021.1's _set_arg*multi interface for CL arg passing

loopy/target/execution.py
Fixes https://github.com/illinois-ceesd/mirgecom/issues/208 , fixes https://github.com/inducer/loopy/issues/208.
@MTCam Can you check if this fixes it for you as well?
@inducer I'm not sure if we need to increment the `DATA_MODEL_VERSION`. Also, it might be interesting to add the skip_arg_checks mode to CI.
Edit: you might need to run with `LOOPY_NO_CACHE=1`
=> fix generate_integer_arg_finding_from_strides in opt case

loopy/kernel/creation.py, loopy/symbolic.py
- computes BatchedAccessRangeMapper.access_maps instead of access_ranges
- BatchedAccessRangeMapper.access_range can derives result from the access_maps
=> BatchedAccessRangeMapper: interfacial changes

test/test_loopy.py
These were deprecated in numpy 1.20.
=> Remove uses of deprecated np.PYTPES in test_pow

loopy/kernel/instruction.py, loopy/preprocess.py, test/test_loopy.py
Closes #231. Closes https://github.com/inducer/pytential/issues/57.
=> Make reduction accumulators not inherit predicates

loopy/schedule/__init__.py
This becomes a 25% performance improvement for sumpy indirectly
because this preserves the insns in the original order that sumpy
kernel was created and that provides a good heuristic for
schedule_as_many_insns_as_possible which bails after 5 insns
that are out of order.
=> Use a better key for compute_topological_order

loopy/symbolic.py, test/test_loopy.py
Necessary because while printing out a reduce(..) we print out the reduction inames to be a list.
=> Accept list of reduction inames in reduction nodes

loopy/kernel/tools.py
loopy is creating a lot of temporary kernels when realizing
lots of reductions in sumpy kernels. Therefore calculating the
global barrier order is expensive.
=> Exit early in getting most recent global_barrier if no barriers exist at all

doc/ref_kernel.rst, loopy/__init__.py, loopy/frontend/fortran/translator.py, loopy/kernel/creation.py, loopy/kernel/instruction.py, loopy/kernel/tools.py, loopy/match.py, loopy/statistics.py, loopy/symbolic.py, loopy/target/c/codegen/expression.py, loopy/target/ispc.py, loopy/tools.py, loopy/transform/data.py, loopy/transform/instruction.py, setup.py, test/test_target.py
=> No more string tags

loopy/target/opencl.py, loopy/target/pyopencl.py, test/test_target.py
Apparently loopy did not support bool types for OpenCL targets. The provided regression with this PR fails on `main`.
=> Bool support opencl target

loopy/kernel/tools.py, loopy/preprocess.py
This makes the assumption that preprocess_kernel doesn't somehow add a global barrier if the original kernel didn't have one.
Not sure if this assumption is correct.
=> Reduce calls to find_most_recent_global_barrier

loopy/kernel/__init__.py, test/test_loopy.py
=> Do not carry over _cached_written_variables with copy, add test that it doesn't survive transformations

loopy/kernel/__init__.py
I don't know why this was not used.
cc @kaushikcfd
=> Fix performance of LoopKernel.all_inames

loopy/kernel/instruction.py, loopy/symbolic.py, loopy/transform/iname.py
Since get_dependencies is cached from a previous invocation,
calling get_dependencies is cheap.
=> Exit early in split_iname if insn doesn't have iname in dependencies

loopy/target/c/__init__.py, loopy/target/c/codegen/expression.py, loopy/target/pyopencl.py
`self.infer_type(expr)` is expensive and is not necessary in kernels without complex numbers
=> Add wrap_in_typecast_lazy

examples/fortran/matmul-driver.py
`parse_fortran` returns a Program instead of a list of kernels
=> Kernel callables: Pass examples

loopy/target/c/__init__.py
In Firedrake we pass Kernel args which have a dtype which is inherited from OpaqueType. On the kernel edit branch I run into an error in the preamble generation when loopy tries to access the numpy_dtype on an OpaqueType.
@kaushikcfd For reproduction of the error: I ran the Firedrake test tests/slate/test_assemble_tensors.py::test_assemble_matrix[cg1-False].
=> Fix C99 preamble generation when args are OpaqueTypes

loopy/codegen/__init__.py, loopy/codegen/control.py, loopy/codegen/result.py
0bd17a4: should address the current CI failure in the cache behavior runs
b25fb81: undos logic unification of translation-unit CodeGenResult and a single loop kernel code generation result
=> Make TranslationUnitCodeGenResult a separate type

loopy/isl_helpers.py, test/test_isl.py
On main, the following fails intermittently:
```python
from loopy.symbolic import parse
from loopy.isl_helpers import simplify_via_aff
expr = parse("i+i_0")
assert simplify_via_aff(expr) == expr
```
=> Make simplify_via_aff deterministic

loopy/target/c/__init__.py, test/test_expression.py
Hi. Firedrake complex was failing tests, because `abs` instead of `cabs` was being used. This PR is fixing that.
=> Fix complex abs.

loopy/transform/fusion.py, test/test_fusion.py
Includes two unit tests (one simple, and one slightly more complex) which fail on `main` without this update. Closes: https://github.com/inducer/loopy/issues/356
=> Add dependencies from accessors to writers when doing kernel fusion

loopy/check.py, test/test_callables.py
=> [callables] Use simplify_via_aff instead of distribute to simplify affine expressions

loopy/target/execution.py, loopy/target/pyopencl.py, loopy/target/pyopencl_execution.py
Together with https://github.com/inducer/meshmode/pull/180, this should help make the array constructor a much smaller factor in our profiles.
cc @matthiasdiener
=> Use pyopencl Array constructor fast path in invoker

loopy/schedule/__init__.py, test/test_callables.py
- Target #222 
Also gets rid of false advertising of calling a kernel as `thrice`, when it really was a `twice` kernel.
=> [callables] Account for callables_table within cache_key before linearization

loopy/kernel/function_interface.py, loopy/type_inference.py
Targets #222 
Passes the "Benchmarks CI": https://gitlab.tiker.net/inducer/loopy/-/jobs/276524
=> [callables] Adds an early exit criterion for a translation unit's type-inference

loopy/codegen/__init__.py, loopy/target/execution.py, loopy/transform/iname.py
=> [callables] KernelState.SCHEDULED -> KernelState.LINEARIZED

loopy/auto_test.py, loopy/check.py, loopy/codegen/__init__.py, loopy/codegen/control.py, loopy/codegen/loop.py, loopy/codegen/result.py, loopy/codegen/tools.py, loopy/kernel/__init__.py, loopy/kernel/tools.py, loopy/schedule/__init__.py, loopy/schedule/device_mapping.py, loopy/schedule/tools.py, loopy/statistics.py, loopy/target/c/__init__.py, loopy/target/cuda.py, loopy/target/execution.py, loopy/target/opencl.py, loopy/transform/save.py, test/test_loopy.py, test/test_target.py, test/test_transform.py
- accessing LoopKernel.schedule warns about its deprecation
- sed commands:
git grep -l "l\.schedule\b" | xargs sed -i \
"s/l.scheduled/linearization/g"
cd test/
git grep -l "get_one_scheduled_kernel" | xargs sed -i \
"s/get_one_scheduled/get_one_linearized/g"
Also updated LoopKernel.hash_fields
=> Do not access LoopKernel.schedule

loopy/transform/add_barrier.py
@inducer I also fixed another issue. Previously, if you didn't pass anything for `insn_before` and `insn_after`, these default to the empty string, so the default match condition is to match *all* instructions (because that's what happens when you pass the empty string to `parse_match()`; side note: this is also what happens if you pass None. `parse_match` really wants to match things). In the case of a kernel with a single instruction (like the FD wave stencil example), this match condition matches the same instruction for both `insn_before` and `insn_after`, which results in a dependency cycle from stmt->barrier and from barrier->stmt. It seems to me that there should be a way to avoid creating either or both of these dependencies when calling `add_barrier`, so I changed it to check …
=> Accept within_inames arg in add_barrier()

loopy/isl_helpers.py, loopy/kernel/creation.py, test/test_callables.py
Targets #222
Turns out we were doing fine. For the test case we generate the following code. What isn't represented in the domain, we cover it up by setting the strides correctly.
```c
static void squared_arange(__global int *__restrict__ y);
__kernel void __attribute__ ((reqd_work_group_size(1, 1, 1))) loopy_kernel(__global int *__restrict__ Y)
{
for (int i_init = 0; i_init <= 39; ++i_init)
Y[i_init] = 1729;
squared_arange(&(Y[0]));
}
static void squared_arange(__global int *__restrict__ y)
{
for (int i = 0; i <= 13; ++i)
y[3 * i] = i * i;
}
```
=> [callables] Test kernel call with non 1-step slice

loopy/check.py, loopy/codegen/__init__.py, loopy/codegen/control.py, loopy/codegen/loop.py, loopy/codegen/result.py, loopy/codegen/tools.py, loopy/kernel/__init__.py, loopy/kernel/tools.py, loopy/schedule/__init__.py, loopy/schedule/device_mapping.py, loopy/schedule/tools.py, loopy/statistics.py, loopy/target/c/__init__.py, loopy/target/cuda.py, loopy/target/opencl.py, loopy/transform/save.py, test/test_loopy.py
=> Acually deprecate `LoopKernel.schedule`

loopy/__init__.py, loopy/check.py, loopy/codegen/bounds.py, loopy/codegen/control.py, loopy/codegen/loop.py, loopy/kernel/__init__.py, loopy/kernel/data.py, loopy/kernel/tools.py, loopy/options.py, loopy/preprocess.py, loopy/statistics.py, loopy/target/ispc.py, loopy/transform/iname.py, loopy/transform/precompute.py, loopy/transform/save.py, test/test_transform.py
This PR makes the ability for users to apply their own tags to inames actually useful. 6441d83 and 3407391 are the two important bits.  In addition, this PR deprecates everything called `IndexTag` (for 2022) in favor of `InameTag` (d164bf3).
3a747fd  and 7b7c44f contain drive-by fixes.
@kaushikcfd, if you like, I can pick this apart into multiple PRs, but I figure reviewing commit-by-commit is maybe not too bad, and I hope these changes will be largely uncontroversial. I'm aware that the rename might cause some conflict with what you're currenty working on, but it's hopefully easy to mop up.
=> Actual support for user-defined iname tags, IndexTag -> InameTag

loopy/codegen/__init__.py, loopy/kernel/creation.py, loopy/preprocess.py, loopy/target/execution.py, loopy/target/pyopencl.py, loopy/target/pyopencl_execution.py, loopy/transform/buffer.py, loopy/transform/data.py, loopy/types.py, setup.py, test/test_linalg.py
- Drop target from types
- Drop prepare_for_caching
- Drop device from PyOpenCLTarget
Closes #411.
Draft because we still need to figure out when numpy fixed the bug described in https://github.com/inducer/loopy/issues/411#issuecomment-860253458 and add that as a dependency. @isuruf, could you investigate?
Draft because:
cc @isuruf
=> Simplifications around Targets

loopy/transform/iname.py
`remove_unused_inames` doesn't like `TranslationUnit`s. I infer that it should be decorated with `for_each_kernel` - feel free to close if not (in which case, what would be the proper way to use the transformation?).
=> Decorate remove_unused_inames with for_each_kernel

loopy/kernel/__init__.py, loopy/kernel/array.py, loopy/kernel/data.py, loopy/kernel/tools.py, loopy/types.py
Various fixes and simplifications. Best read commit-by-commit. I don't imagine any of this is controversial, hence I'm not tagging anyone for review, but maybe you're reading this anyway. :)
The original impetus for this was wanting to actually use argument tagging, and discovering it to be awkwardly broken without 
9ef80b3, and then discovering key conflicts. The rest were incidental fixes following from #419.
=> Tagging and fixes

loopy/target/pyopencl.py, test/test_target.py
-Closes #452.
- Closes https://github.com/inducer/meshmode/issues/237.
=> PyOpenCL executor: accept device scalars for ValueArgs

loopy/__init__.py, loopy/check.py, loopy/cli.py, loopy/codegen/__init__.py, loopy/codegen/instruction.py, loopy/expression.py, loopy/kernel/creation.py, loopy/schedule/__init__.py, loopy/symbolic.py
1. No substantial benefit by avoiding initialization.
2. If pyopencl < 2021.2 is present in the environment, user is forced to upgrade pyopencl even if they just want to use the CTarget.
Reported by @ReubenHill on firedrake slack.
The 3 later commits are intended to placate [N818](https://github.com/PyCQA/pep8-naming#error-codes).
=> Do not set DEFAULT_TARGET in loopy.__init__

loopy/diagnostic.py, loopy/schedule/__init__.py, loopy/symbolic.py
=> Add a compatibility shim for UnableToDetermineAccessRange, ScheduleDebugInput

loopy/kernel/function_interface.py, test/test_callables.py
The provided test fails on `main` with the error:
```
File "/home/kgk2/projects/pytato_multiprogram/src/loopy/loopy/isl_helpers.py", line 645, in get_param_subst_domain                                  
new_subst_dict[new_name] = subst_dict[old_name]                                                                                                   
KeyError: 'n'
```
=> Bugfix: corrects the arg passed to subst_into_pwaff

loopy/target/c/__init__.py, loopy/target/pyopencl.py, test/test_target.py
=> Bugfix: Correct the host/device code generation for global temporaries with base_storage != None

loopy/tools.py
Add `update_for_Map` to `LoopyKeyBuilder`. This will be needed, e.g., once kernel instructions contain the new dependency maps. Merging this as a separate PR will eliminate an entire file from the (upcoming) dependency-checking PR diff, plus it could be useful independently.
This change was previously part of this PR: [Check new dependencies against SIO](https://github.com/inducer/loopy/pull/264)
=> Add update_for_Map to LoopyKeyBuilder

loopy/target/pyopencl_execution.py, test/test_loopy.py
Provided regression fails on [`main`](https://github.com/inducer/loopy/commit/c33406c9098879737bf476380b7e1c53c7c87c78).
=> [pyopencl target]: Fix host code for zero-strided outputs

loopy/__init__.py, loopy/isl_helpers.py, loopy/transform/iname.py, test/test_reduction.py, test/test_transform.py
Add `map_domain` transformation.
This PR/branch is one of **two parents** of [**child PR/branch:  Update dependencies during transformation**](https://github.com/inducer/loopy/pull/279)
This PR/branch was moved here to independent, top-level PR/branch from [**old PR/branch**: Add map_domain transformation](https://github.com/inducer/loopy/pull/300).
Note that to keep these branches independent, some helper functions are defined in both branches.
=> Map domain transformation v2

loopy/__init__.py, loopy/symbolic.py, loopy/transform/instruction.py, test/test_transform.py
`lp.simplify_indices` would simplify the indexing expressions. Typically helpful if one wants to look at a kernel with redundant expressions in the subscripts
=> Implements `lp.simplify_indices`.

loopy/kernel/instruction.py
Should help avoid some expression traversals `if not __debug__`.
=> Assignment.sub_array_ref_inames: avoid expression traversals

loopy/kernel/array.py
Previously `__hash__` was implicitly set to `None` because `ArrayBase` only implemented `__eq__`.
Fixes #523
=> Make ArrayBase hashable

loopy/transform/iname.py, test/test_transform.py
- Attached regression fails on `main`.
Q. Aren't reduction inames included in an instruction's dependencies?
A. Apparently not, see `DependencyMapper.map_reduction`: https://github.com/inducer/loopy/blob/125bc1f24818c9c038ccfb64aaf71e3c4908f322/loopy/symbolic.py#L406-L408
=> lp.rename_iname: support renaming reduction iname.

loopy/preprocess.py, test/test_reduction.py
Reported by @majosm.
Encountered in https://github.com/illinois-ceesd/mirgecom/pull/579.
=> Test, fix reductions with no inames

loopy/target/pyopencl_execution.py
After we removed the special unpickling behavior for dtypes, https://github.com/numpy/numpy/issues/4317 was back on the table. This introduces a different test for built-in-ness that seems more robust, for now.
cc @matthiasdiener
=> Fix test for numpy builtin type to avoid numpy#4317

loopy/isl_helpers.py, loopy/kernel/tools.py, loopy/symbolic.py, loopy/transform/realize_reduction.py
As of islpy 2022.1 / https://github.com/inducer/islpy/pull/85, islpy packages its error messages into the exception like a normal library, rather than spewing them onto stderr. That makes uses of `isl.SuppressedWarnings` moot (which is also now deprecated).
=> Drop uses of islpy.SuppressedWarnings (deprecated, now a no-op)

loopy/transform/subst.py, test/test_loopy.py
This avoids confusion with the names already present in the kernel.
On main:
```python
t_unit = lp.make_kernel(
"{[i]: 0<=i<10}",
"""
<> tmp[i] = 2*i
out[i] = 2*tmp[i]
""")
t_unit = lp.assignment_to_subst(t_unit, "tmp")
```
would yield:
```
---------------------------------------
DOMAINS:
{ [i] : 0 <= i <= 9 }
---------------------------------------
INAME TAGS:
i: None
---------------------------------------
SUBSTITUTION RULES:
tmp_subst(i) := 2*i
---------------------------------------
INSTRUCTIONS:
for i
out[i] = 2*tmp_subst(i)  {id=insn_0}
end i
---------------------------------------
```
Notice how the substitution argument is 'i' and the kernel contains 'i'
as a domain dim.
=> [assignment_to_subst] rename subst arguments

loopy/codegen/__init__.py
Avoids redundant linearization, if a kernel is already marked as linearized.
=> [perf] Codegen: Linearize only if needed

loopy/target/pyopencl.py, test/test_target.py
This came up in putting together https://github.com/inducer/meshmode/pull/312.
=> PyOpenCL invoker: tolerate zero-size temporaries

loopy/kernel/__init__.py
Noticed that it had a marginally helpful message of `LoopKernel.linearization is deprecated, use LoopKernel.linearization instead` :grin:
=> Fix LoopKernel.schedule deprecation warnings

doc/tutorial.rst, loopy/target/c/codegen/expression.py, test/test_loopy.py
Avoids warnings of the type
`warning: pocl-cache/tempfile_BYDWne.cl:96:2241: operator '?:' has lower
precedence than '*'; '*' will be evaluated first`
=> CExpressionToCodeMapper: clarify precedence in map_if

loopy/target/c/codegen/expression.py
Not all architectures have `np.float128` (e.g., Mac M1)
See e.g. https://github.com/mpi4jax/mpi4jax/issues/112
=> remove float128 reference

.github/workflows/ci.yml, loopy/check.py, loopy/frontend/fortran/translator.py, loopy/kernel/creation.py, loopy/kernel/function_interface.py, loopy/kernel/instruction.py, loopy/preprocess.py, loopy/symbolic.py, loopy/target/c/__init__.py, loopy/tools.py, loopy/transform/iname.py, loopy/transform/privatize.py, loopy/transform/subst.py, setup.py
See https://github.com/inducer/pymbolic/pull/90.
Draft because:
=> Use memoized variants for mapping expressions

loopy/transform/callable.py, test/test_callables.py
The provided test fails on `main`.
=> [callable.inliner] passing scalar for callee's ArrayArgs

loopy/transform/callable.py, test/test_callables.py
The provided test fails on `main` as the predicates are lost, resulting in incorrect results.
/cc @sv2518
=> [callable.inliner, bugfix]: Inlined kernel would lose the predicates surrounding the call instruction

test/test_loopy.py
=> Fix vectorization with predicates

doc/tutorial.rst, loopy/kernel/data.py, loopy/target/c/c_execution.py, loopy/target/execution.py, loopy/target/pyopencl_execution.py, test/test_target.py
@majosm's multi-volume work in mirgecom brought empty arrays into pytato DAGs, which, after https://github.com/inducer/pytato/pull/320, exposed an issue in Loopy's argument handling. It ignored the provided `is_{input, output}` flags (in favor of "whether it's written") when determining when an array is required as input or returned. This logic, of course, falls apart if the array is never written because it's empty.
Best read commit-by-commit. The included regression test fails on 696c6a98e742275de7f9d67769a4011e6e2ba5c0.
=> Argument passing/return: consider `is_{input,output}`

loopy/__init__.py, loopy/target/c/c_execution.py, loopy/target/execution.py, test/test_loopy.py, test/test_target.py
=> Fix stride check for zero-size arrays

loopy/schedule/__init__.py, test/test_loopy.py
This should fix #644.
@kaushikcfd, could you review and add a regression test?
=> Allow leaving 'vec'-tagged loops

loopy/check.py, loopy/target/cuda.py, test/test_loopy.py
See https://github.com/inducer/loopy/discussions/656.
=> [CudaTarget] Macrofies ((int32_t) blockIdx.x) -> bIdx_32(x) to increase SNR in the generated code

.github/workflows/ci.yml
Reverts inducer/loopy#655
Fix has landed in Firedrake.
=> Revert "Avoid failing firedrake gtmg tests"

loopy/preprocess.py, loopy/target/pyopencl_execution.py, requirements.txt, test/test_loopy.py
Manage to track down the failure in inducer/pytential#167 to the way loopy handles zero length arrays with the `sep` tag (not super sure that's related?).
This contains a MWE, but I haven't had the time to get a fix. Any suggestions where to start looking?
=> Fix zero length sep arrays handling

loopy/target/cuda.py, test/test_loopy.py
Address space qualifiers are ignored, so better to not generate them.
```c
(feinsum_env) kgk2@bock:~/temp$ cat ok.cu 
#define bIdx(N) ((int) blockIdx.N)
#define tIdx(N) ((int) threadIdx.N)
extern "C" __global__ void __launch_bounds__(1) foo(int const N, __global__ double *__restrict__ a)
{
a[bIdx(x)] = bIdx(x);
}
(feinsum_env) kgk2@bock:~/temp$ nvcc -c ok.cu 
ok.cu:4:1: warning: ‘global’ attribute directive ignored [-Wattributes]
4 | extern "C" __global__ void __launch_bounds__(1) foo(int const N, __global__ double *__restrict__ a)
| ^
```
@thilinarmtb also pointed kernels with the address space qualifiers raise compilation error with `nvrtc`.
=> CudaTarget: no address space qualifier for arguments

loopy/target/c/__init__.py, loopy/translation_unit.py
Without this, things like the schedule cache will indirectly hold (strong) references to CL contexts, programs and kernels, which means that those will have a hard time getting cleaned up.
=> Use a `WeakKeyDictionary` for `program_executor_cache` to avoid keeping CL contexts alive

loopy/transform/precompute.py, test/test_transform.py
Without this patch could see errors like:
```
loopy.diagnostic.LoopyError: Existing and new dtype of temporary 'L_fetch' do not match (existing: np:dtype('float64'), new: float64)
```
=> Account for TemporaryVariable.dtype to be a NumpyType

loopy/translation_unit.py, test/test_loopy.py
Matches the handling in the base class `ImmutableRecord` at
https://github.com/inducer/pytools/blob/7f5e62f34661a8ef40a0b73e0e7f55b54dbdf95e/pytools/__init__.py#L489-L496
=> Fix TranslationUnit._hash_value disappearing during pickling

loopy/target/pyopencl.py, loopy/translation_unit.py
=> PyOpenCLTarget: do not use the same executor cache key for different entrypoints

loopy/codegen/__init__.py, loopy/codegen/result.py, loopy/target/__init__.py, loopy/target/c/__init__.py, loopy/target/cuda.py, loopy/target/execution.py, loopy/target/ispc.py, loopy/target/opencl.py, loopy/target/pyopencl.py, loopy/target/python.py, test/test_target.py
=> PyOpenCL target: Overflow large argument counts into SVM struct

loopy/kernel/instruction.py
Memoized methods should emit immutable objects.
=> Make reduction inames a frozenset

loopy/target/__init__.py, loopy/target/c/__init__.py, loopy/target/cuda.py, loopy/target/ispc.py, loopy/target/opencl.py, loopy/target/pyopencl.py
Change naming of `is_executable` on Target class to `single_subkernel_is_entrypoint,` add docs and error when there is more than one subkernel.
=> Adress code review comments on branch fix_648

loopy/transform/realize_reduction.py
Add a space between `than` and `one` in Loopy error.
=> Add a space between `than` and `one`

loopy/tools.py
Note that this adds the (unqualified) function name to the name of the cache *and* the function itself to the cache key.
=> `memoize_on_disk`: segregate caches by wrapped function 

loopy/options.py, loopy/target/c/codegen/expression.py, loopy/target/pyopencl.py, setup.py
Needs https://github.com/inducer/pyopencl/pull/651
=> Generate c{double, float}_fma for pyopencl

loopy/transform/iname.py
Picking a deterministic order in which the inames are removed is
*necessary* to ensure that the left over domain is the same across
interpreter runs
=> [lp.remove_unused_inames] Sort the inames before removing them

loopy/isl_helpers.py, test/test_expression.py
This is needed in order to not generate complicated code for values like `(i*(i+1))//2`.
=> Extend nonnegative check to products as well

loopy/__init__.py, loopy/transform/concatenate.py, loopy/transform/merge_arrays.py, loopy/transform/padding.py, test/test_transform.py
Needed for https://github.com/inducer/sumpy/pull/151
=> Add `concatenate_arrays` transformation

loopy/transform/callable.py, test/test_callables.py
Fixes https://github.com/inducer/loopy/issues/728
=> Recurse on stride when inlining

loopy/target/c/__init__.py, loopy/transform/data.py, test/test_loopy.py
cc @kaushikcfd 
Alternate fix for #737. Supersedes #738.
Closes #737.
=> Do not emit temporary decls for temporaries not used in a subkernel 

loopy/type_inference.py, test/test_loopy.py
My understanding of `RuleAwareIdentityMapper` was unclear, which was why I introduced the bug. I fixed it now. (Hopefully, the CI agrees)
Fixes #746.
=> Correctly handle type inference of substitution rules

loopy/codegen/__init__.py, loopy/schedule/__init__.py
Makes the logging more consistent with cache hits, and more consistent with the typed-and-scheduled and invoker cache logging.
=> schedule, codegen: log cache misses

loopy/codegen/instruction.py, loopy/target/opencl.py
=> Hack around nameless isl `Set` equality in implemented-domain caching

loopy/codegen/bounds.py, loopy/codegen/loop.py, loopy/codegen/tools.py, loopy/schedule/__init__.py, loopy/target/cuda.py, loopy/target/opencl.py, test/test_loopy.py
Closes #724.
This is an alternative to #751.
=> `get_usable_inames_for_conditional`: allow only 'related' parallel inames

loopy/transform/instruction.py
Currently `replace_instruction_ids` only updates the instruction ids in an instruction's `depends_on` set and `no_sync_with` set. It doesn't actually update the id property of an instruction, which for me seems unintuitive. This change adds this capability and some documentation for `replace_instruction_ids`.
=> Update insn ids in addition to updating dependency ids in replace_instruction_ids

loopy/symbolic.py
Following the discussion in #794, adds `minimum` and `maximum` as scalar callables to `map_call` in the function to primitive mapper.
=> Add scalar minimum/maximum to function mapper

doc/ref_kernel.rst, loopy/codegen/control.py, loopy/codegen/loop.py, loopy/kernel/data.py, loopy/target/__init__.py, loopy/target/c/__init__.py, loopy/target/ispc.py, loopy/target/opencl.py, loopy/target/python.py, test/test_loopy.py
Fixes https://github.com/inducer/loopy/issues/782
For C:
#pragma unroll
and for OpenCL
__attribute__((opencl_unroll_hint))
=> Add UnrollHintTag for #pragma unroll and opencl_unroll_hint

loopy/transform/privatize.py
This is done for privatizing, but not for unprivatizing in main.
=> Forget about strides in dim tags when unprivatizing

loopy/transform/iname.py
Adds keyword parameter to `rename_iname` so raise_on_domain_mismatch can be passed into the call to `rename_inames`.
=> Add raise_on_domain_mismatch parameter to rename_iname

loopy/kernel/creation.py
Mysteriously, this fixes a doc build failure in grudge with a backtrace saying
``` 
File /home/runner/work/grudge/grudge/.conda-root/envs/testing/lib/python3.11/site-packages/loopy/kernel/creation.py, line 2329, in <dictcomp>
getattr(loopy.version, lvs): lvs
^^^^^^^^^^^^^
AttributeError: module 'loopy' has no attribute 'version'
```
Build failure: https://github.com/inducer/grudge/actions/runs/5915142781/job/16041111199#step:3:1191
=> Fix import of `loopy.version`

setup.cfg
With this change, one can run `pytest` directly in the main dir of loopy (without specifying the test dir).
=> ignore proto-tests/, ndarray/ dirs for pytest

loopy/target/c/__init__.py
To my eye it appears we can move the `x*x` outside of the if-else block and eliminate the else branch.
=> Simplify float, int power function

loopy/target/execution.py
`__init__()` methods should not return anything.
Further, `return None` is a noop anyway :).
=> Fix violations of Flake8 Bugbear B037

loopy/codegen/loop.py, loopy/kernel/tools.py, loopy/schedule/tools.py, test/test_loopy.py
=> Access Race Checker: account for non-zero hardware axes lower bounds

doc/tutorial.rst, loopy/schedule/tools.py, test/test_loopy.py
Provided test case fails on `main`.
Draft because:
- Fix for #600 must land first as it has broken out CI.
=> write race checking: tighten condition based on address space

loopy/version.py
Could we also have a version bump on pypi. Thanks! (See https://github.com/inducer/loopy/issues/159#issuecomment-1467136411)
=> Bump version to 2024.1

loopy/kernel/instruction.py
This doesn't change all occasions of `isinstance(..., frozenset)`, just the ones necessary to work with https://github.com/matthiasdiener/orderedsets in pytato.
=> change isinstance(..., frozenset) to isinstance(..., abc.Set)

loopy/target/c/c_execution.py, test/test_c_execution.py
This doesn't seem to be used anywhere -- the `CCompiler` class has its own `source_suffix` argument.
xref: Tried to remove `pytools.Record` from `codepy` and this field was added only here.
Needs inducer/arraycontext#252.
=> c_execution: remove unused source_suffix argument to GCCToolchain

loopy/target/__init__.py, loopy/target/pyopencl.py, loopy/target/python.py
Not sure if I just have a newer `mypy` version, but it was complaining about these and it seemed to make sense.
=> Fix some annotations in loopy.target

doc/ref_other.rst, loopy/__init__.py
cc: https://github.com/inducer/pyopencl/pull/737
Note: In contrast to pyopencl, loopy caching can be enabled/disabled during execution; as far as I can tell there is no good way to avoid creating the empty caches when running with an environment variable set to disabling caching at startup.
=> {LOOPY,CG}_NO_CACHE: allow re-enabling the cache with False value

loopy/symbolic.py
Should address failures like
```
pymbolic.mapper.UnsupportedExpressionError: <class 'loopy.kernel.tools._IndexCollector'> cannot handle expressions of type <class 'loopy.symbolic.TypeCast'>
```
observed in e.g. [this run](https://github.com/illinois-ceesd/mirgecom/actions/runs/9626097768/job/26924869997?pr=926)
NB: `_IndexCollector` is not in main (yet?), it was added in @kaushikcfd's loop fusion branch.
cc @mtcam @matthiasdiener
=> Support `TypeCast` in `CombineMapper`

loopy/kernel/instruction.py
cc @MTCam
Needed due to https://github.com/illinois-ceesd/meshmode/blob/e7337041c950fc45a86ca39235e929a5733ee620/meshmode/array_context.py#L1165 - not sure how that worked before.
Perhaps related to #850 or #853.
=> InstructionBase: implement _with_new_tags

loopy/type_inference.py
9f2e8ce2a13835e7e6d8529b500a7076a9b9f415 broke some mirgecom [runs](https://github.com/illinois-ceesd/mirgecom/actions/runs/9997932395/job/27640650287?pr=1047):
```console
[...]
File "/home/runner/work/mirgecom/mirgecom/src/loopy/loopy/type_inference.py", line 329, in map_sum
dtype_set = self.rec(child)
^^^^^^^^^^^^^^^
File "/home/runner/work/mirgecom/mirgecom/src/pymbolic/pymbolic/mapper/__init__.py", line 271, in __call__
result = method(expr, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/mirgecom/mirgecom/src/loopy/loopy/type_inference.py", line 400, in map_type_cast
raise LoopyError(f"Can't cast a '{subtype}' to '{expr.type}'")
loopy.diagnostic.LoopyError: Can't cast a 'np:dtype('bool')' to 'np:dtype('float64')'
```
=> TypeInferenceMapper: allow np.bool in map_type_case

loopy/kernel/creation.py, loopy/transform/iname.py, test/test_transform.py
* Changed to update the inames of the instructions that do not access an inames, yet, are nested within the iname to be duplicated.
* Closes #859
=> Fix _InameDuplicator.within

loopy/target/c/__init__.py, loopy/target/cuda.py, loopy/transform/data.py
1. Fix Aliased scratchpad CUDA variables.
2. Better error message for non-type-inferred kernels with allocate_temp_base_storage.
Closes <https://gitlab.tiker.net/inducer/loopy/-/issues/205>.
=> Some bugfixes.

test/test_loopy.py
On Python 3.12, this provokes a stack overflow in the scheduler. It is not quite clear why that's the case; pure-Python recursion even with generators seems to respond well to setrecursionlimit():
```py
def f(n):
if n:
yield from f(n-1)
else:
yield 5
import sys
sys.setrecursionlimit(3500)
print(list(f(3400)))
```
That said, there have been [behavior](https://github.com/python/cpython/pull/96510) [changes](https://github.com/python/cpython/issues/112215) in Py3.12 in this regard, but it is not clear what exactly about Loopy's behavior makes it fall into the 'bad' case.
This is a smaller reproducer of an issue flagged by @a-alveyblanc in the context of tensor product code generated from Pytato.
It appears that Py3.12 [will receive some …
=> Add `test_long_kernel`

loopy/kernel/instruction.py, loopy/tools.py, pyproject.toml
Closes #865.
Given that happens_after is a sufficiently big change, I suggest we release a new version.
=> Require that happens_after is not mutable

loopy/transform/pack_and_unpack_args.py
`pack_and_unpack_args_for_call_for_single_kernel ` was missing the documentation for `args_to_pack` and had two different definitions of `args_to_unpack`.
=> Update documentation in pack_and_unpack_args

loopy/schedule/tools.py, loopy/statistics.py, loopy/transform/precompute.py, loopy/transform/privatize.py, loopy/transform/realize_reduction.py
Follow-up to #872, for compatibility with https://github.com/inducer/pymbolic/pull/152.
=> Even moar flatten

loopy/symbolic.py
This restores compatibility with pymbolic 2022.2.
x-ref: https://github.com/firedrakeproject/loopy/issues/27
Mypy failure is expected, won't be fixed until #868 goes in.
cc @connorjward
=> Un-type `symbolic.flatten`

doc/conf.py, loopy/__init__.py, loopy/check.py, loopy/codegen/__init__.py, loopy/frontend/fortran/expression.py, loopy/kernel/__init__.py, loopy/kernel/array.py, loopy/kernel/data.py, loopy/kernel/function_interface.py, loopy/kernel/instruction.py, loopy/library/reduction.py, loopy/symbolic.py, loopy/target/c/__init__.py, loopy/target/c/codegen/expression.py, loopy/target/execution.py, loopy/target/ispc.py, loopy/target/pyopencl_execution.py, loopy/target/python.py, loopy/tools.py, loopy/transform/array_buffer_map.py, loopy/transform/callable.py, loopy/transform/concatenate.py, loopy/transform/data.py, loopy/transform/precompute.py, loopy/type_inference.py, loopy/types.py, loopy/typing.py, pyproject.toml
=> Pymbolic typing

loopy/schedule/__init__.py, loopy/schedule/tree.py, loopy/transform/precompute.py
- Replace most of `typing.*` with `collections.abc.*`
- Make return types concrete, arguments abstract
- Replace `Optional` with `| None`
=> schedule: update types

loopy/tools.py
```python
from loopy.tools import LazilyUnpicklingList, LazilyUnpicklingDict, _PickledObject
l = LazilyUnpicklingList([1, 2, 3, 4])
print(l)
d = LazilyUnpicklingDict({'a':1, 'b':2})
print(d)
p = _PickledObject(7)
print(p)
```
before:
```
<loopy.tools.LazilyUnpicklingList object at 0x101810810>
<loopy.tools.LazilyUnpicklingDict object at 0x104b2ccd0>
<loopy.tools._PickledObject object at 0x10103a450>
```
after:
```
LazilyUnpicklingList([1, 2, 3, 4])
LazilyUnpicklingDict({'a': 1, 'b': 2})
_PickledObject(7)
```
(If you want, I could add `__str__` methods that don't include the class names.)
=> LazilyUnpickling{Dict,List}: add __repr__

loopy/kernel/__init__.py, loopy/schedule/__init__.py
This was raising a large number of warnings in our CI.
I assume that it is fine to remove code slated for removal nearly 3 years ago.
=> Remove kernel.schedule (deprecated)

loopy/schedule/tree.py
- make dataclass non-frozen
- use mutate() for cases where a Map is modified multiple times
- remove asserts for cases that would fail immediately anyway
---
For the following microbenchmark:
```python
from loopy.schedule.tree import Tree
def run_t():
tree = Tree.from_root(-1)
for i in range(100):
tree = tree.add_node(i, i-1)
for i in range(100):
tree = tree.replace_node(i, 101+i)
for i in range(100):
tree = tree.move_node(101+i, -1)
from timeit import timeit
print(timeit(run_t, number=1000))
```
, this PR results in performance improvements:
| Branch       | Without -O | With -O |
|----------------|-------------|--------|
| main           | 0.495       | 0.435  |
| tree-speedups ([78c19c8](https://github.com/inducer/loopy/pull/887/commits/78c19c8d973dcdd47b466f1c5d0cf634f6fa4c70)) | …
=> Tree: various speedups

loopy/kernel/function_interface.py, loopy/library/random123.py
This reverts commit 1af452302afdc8558773b503f621c08859565539.
=> Revert "Hack dataclass'd function_interface to avoid breaking Firedrake"

.github/workflows/ci.yml
Closes #891 
In this change we switch to running the "smoke tests" that Firedrake encourages users to do: https://www.firedrakeproject.org/firedrake/download.html#testing-the-installation
Note that tests are currently failing because of the reason [discussed here](https://github.com/inducer/loopy/pull/886#issuecomment-2507860688). This PR can probably follow any other fixes to loopy/Firedrake.
=> Run parallel Firedrake tests in CI

loopy/codegen/control.py
We have been generating slightly different code on different ranks because predicates are stored as a frozenset.
=> Sort predicates in codegen so they are consistent in parallel

loopy/statistics.py
Counting ops currently fails when a type cast operation is encountered. This considers the cost of type casting to be free.
=> Handle type casting in op counter

examples/python/call-external.py, loopy/kernel/function_interface.py, loopy/library/function.py, loopy/library/random123.py, loopy/library/reduction.py, loopy/target/c/__init__.py, loopy/target/opencl.py, loopy/target/pyopencl.py, test/library_for_test.py, test/testlib.py
This uses `immutabledict` whenever possible. It's not exactly clear to me if some of these should be passed in as immutable higher up the stack, so someone more knowledgeable should have a serious look.
Fixes #905.
=> Pass immutable arg_id_to_dtype to InKernelCallables

loopy/target/c/c_execution.py
xref: https://github.com/inducer/codepy/pull/51
=> Remove use of deprecated wait_on_error from codepy

pyproject.toml
With this change, one can run `pytest` directly in the main directory of loopy (without specifying the `test/` dir).
cf. https://github.com/inducer/loopy/pull/804
=> ignore proto-tests/ for pytest

loopy/transform/diff.py, pyproject.toml, test/test_callables.py, test/test_diff.py, test/test_einsum.py, test/test_expression.py, test/test_fusion.py, test/test_loopy.py, test/test_reduction.py, test/test_scan.py, test/test_target.py, test/test_transform.py
Enables `NPY002` and uses `np.random.default_rng()` with a seed everywhere.
=> Use default_rng in tests

loopy/target/c/c_execution.py
This small PR resolves the deprecation warning coming from `logger.warn`:
```python
The 'warn' method is deprecated, use 'warning' instead
```
=> feat: replace use of deprecated logger.warn

doc/ref_transform.rst, loopy/__init__.py, loopy/auto_test.py, loopy/check.py, loopy/kernel/__init__.py, loopy/kernel/creation.py, loopy/kernel/data.py, loopy/kernel/function_interface.py, loopy/kernel/tools.py, loopy/match.py, loopy/schedule/__init__.py, loopy/schedule/tools.py, loopy/symbolic.py, loopy/transform/iname.py, loopy/transform/loop_fusion.py, loopy/transform/parameter.py, loopy/transform/subst.py, loopy/typing.py, pyproject.toml, test/test_loop_fusion.py
Loopy-flavored loop-fusion transformation corresponding to <https://doi.org/10.1007/3-540-57659-2_18>.
=> Implements a Loop Fusion Transformation
