inducer/loopy

loopy/auto_test.py
auto_test_vs_ref now returns a dictionary mapping strings to various timings
=> updated auto_test_vs_ref to return a dictionary of computed times

doc/reference.rst, doc/tutorial.rst, loopy/__init__.py, loopy/compiled.py, loopy/statistics.py, test/test_statistics.py
added docstrings and tutorial section for statistics gathering functions
=> added docstrings and tutorial section for statistics gathering functions

loopy/kernel/tools.py
Added _add_dtypes_overdetermined which accepts dicts that have unused arguments.
To avoid duplicating code, I created _add_dtypes, which does everything that add_dtypes used to do, minus the error check. Now add_dtypes and _add_dtypes_overdetermined call _add_dtypes. _add_dtypes_overdetermined is called by _add_and_infer_dtypes_overdetermined.
As far as I can tell, this won't show up in the documentation.
If you'd prefer a different refactoring of the code just let me know.
=> added version of add_and_infer_dtypes that accepts type dicts with unused args

loopy/statistics.py, test/test_statistics.py
Uniform loads only counted once per thread workgroup.
Did I memoize correctly? Will get_insn_count only execute once with uniform=True and once with uniform=False (per call to get_gmem_access_poly)?
=> uniform loads only counted once per thread work group

loopy/preprocess.py
=> [bugfix] Fix interplay of reduction operations and forced iname deps

doc/misc.rst
This pointed to the PyPI link for another of your projects.
=> Update bad link

loopy/kernel/data.py
=> [bugfix] Fix CallInstruction for temp_var_types=None

loopy/codegen/control.py, loopy/kernel/__init__.py, loopy/kernel/creation.py, loopy/kernel/instruction.py, loopy/version.py, test/test_loopy.py
I have added a test for loop unrolling as referenced in #37.
Additionally, I have expanded the IF_RE regex to recognize sub-scripted predicates.
I had to work from a slightly older commit (2e56272) as it appears some of the newer commits have broken things (at least on my system)
=> Fixes issue #37

loopy/target/c/__init__.py, loopy/target/cuda.py
This adds support for constant arguments to the CTarget, and fixes the CUDA constant arg declaration
=> Add implementation of constant args to CAST

loopy/target/cuda.py
Import was from incorrect place
=> Fix for wrap_global_constant in CudaTarget

test/test_fortran.py
=> DIsable test_fortran.py:test_matmul on Pocl due to crashes

loopy/kernel/tools.py
=> Use pytools.graph.compute_topological_order()

examples/fortran/matmul.floopy, examples/python/rank-one.py, loopy/check.py, loopy/kernel/creation.py, loopy/kernel/instruction.py, loopy/maxima.py, loopy/options.py, loopy/preprocess.py, loopy/schedule/__init__.py, loopy/statistics.py, loopy/transform/iname.py, loopy/transform/save.py, loopy/version.py, test/test_apps.py, test/test_dg.py, test/test_domain.py, test/test_fortran.py, test/test_linalg.py, test/test_nbody.py, test/test_numa_diff.py, test/test_sem_reagan.py, test/test_target.py, test/test_transform.py
Reverts inducer/loopy#120
Should've been more cautious. @kaushikcfd, the bug you pointed out actually [broke pytential](https://github.com/inducer/pytential/runs/864088955).
Reverting for now, we can think more carefully about this in the morning.
=> Revert "Purge boostability"

loopy/__init__.py, loopy/transform/iname.py, loopy/type_inference.py, requirements.txt, test/test_transform.py
Step 1 of reviving #120 to get us a softer version of purging boostability.
=> New transform: broadcast_along_unused_hw_axes

loopy/statistics.py
=> Stride finding improvements

doc/tutorial.rst, loopy/schedule/__init__.py, loopy/symbolic.py, setup.py
Based off of [a previous MR](https://gitlab.tiker.net/inducer/loopy/-/merge_requests/388).
=> Scheduler optimization: scheduling multiple run instructions at once

loopy/symbolic.py, loopy/transform/iname.py, test/test_loopy.py
=> Fix split iname within

loopy/kernel/array.py, loopy/kernel/data.py, setup.py
=> Revert "Add tags to Loopy"

requirements.txt
h/t @matthiasdiener https://github.com/illinois-ceesd/mirgecom/pull/162
=> Add '#egg=' tag to f2py requirement

loopy/kernel/array.py, loopy/kernel/data.py, loopy/version.py, requirements.txt, setup.py
Reverts inducer/loopy#172, originally in #156.
=> Reinstate "Add tags to Loopy""

loopy/type_inference.py, test/test_statistics.py
=> Fix constant type inference in float context

.github/workflows/ci.yml, doc/ref_kernel.rst
@jdsteve2 @kaushikcfd What do you think of this?
=> Description of computations expressible in Loopy

loopy/target/pyopencl.py
=> Use set arg buf in pyopencl invoker

loopy/target/pyopencl.py
=> Use positional args in enqueue_nd_range_kernel in invoker

loopy/options.py, loopy/target/execution.py
=> Determine skip_arg_checks default according to value of python -O flag

loopy/schedule/__init__.py
Fixes https://github.com/inducer/loopy/issues/199
=> Compare insns by id only for list remove

loopy/statistics.py, test/test_statistics.py
=> [Statistics]: Handle instructions not with empty loop domain

.github/workflows/ci.yml, .gitlab-ci.yml, loopy/options.py, loopy/target/execution.py, test/test_loopy.py
cc  @matthiasdiener @mtcam 
x-ref: #210
=> Check env var _LOOPY_SKIP_ARG_CHECKS for skip_arg_checks option default

.github/workflows/ci.yml
Inspired by https://github.com/inducer/pytential/pull/56
=> Add CI jobs for downstream projects

loopy/frontend/fortran/tree.py
=> Some fixes to the fortran parser to get NPB/LU/buts to parse

loopy/kernel/__init__.py, loopy/statistics.py
=> LoopKernel.get_grid_size_upper_bounds: always return PwAff

loopy/codegen/__init__.py, test/test_c_execution.py
=> CTarget: Get compilable code with for loops with loop-count == 1

loopy/target/c/__init__.py, loopy/target/c/c_execution.py, loopy/target/c/codegen/expression.py, loopy/target/execution.py, loopy/target/pyopencl.py, test/test_c_execution.py, test/test_expression.py, test/test_target.py
Extends @dham's work at https://github.com/firedrakeproject/loopy/pull/3.
=> Add complex dtype support to C99 target

loopy/check.py, loopy/version.py
=> Kill heuristics-based redundant execution along hw axes ('boosting')

loopy/target/c/__init__.py, loopy/target/c/c_execution.py
Closes #253.
cc @bourdin @wence-
=> Use real128 only if present in numpy

.github/workflows/ci.yml, loopy/auto_test.py
=> Add Github CI run on Intel CL

loopy/transform/iname.py
Cherry picks @isuruf's commits.
=> Fix no within iname transforms

loopy/expression.py, loopy/target/c/codegen/expression.py, loopy/target/ispc.py, test/test_expression.py
Attached test fails on `main`.
=> [c codegen] Account for bool type contexts

loopy/target/c/codegen/expression.py, test/test_expression.py
=> Handle instances of np.bool_ in statements' expression trees

loopy/transform/iname.py
=> Document join inames, fix markup in get_iname_duplication_options

loopy/check.py
=> Make discard_dep_reqs_in_order faster

loopy/kernel/creation.py, loopy/kernel/tools.py
=> Make guess_var_shape work on multiple var_names simultaneously

loopy/symbolic.py, loopy/transform/iname.py
=> Do not map args, tvs in split_iname

loopy/library/reduction.py, test/test_nbody.py
=> Drop forced_result_type in reductions

loopy/codegen/__init__.py, loopy/target/python.py
=> Clarify seen function callable interaction

doc/conf.py, doc/index.rst, doc/ref_call.rst, doc/ref_program.rst, doc/tutorial.rst, loopy/kernel/function_interface.py, loopy/library/reduction.py, loopy/program.py, loopy/statistics.py, loopy/symbolic.py
=> Pass Docs CI

loopy/kernel/creation.py, test/library_for_test.py, test/test_callables.py
=> [callables] Test mangled symbol input to call

loopy/target/c/__init__.py, test/test_expression.py
=> CTarget: add support for conj

loopy/target/pyopencl.py, loopy/type_inference.py
* If need be, this criterion should be handled by callables themselves
Targets #222
=> [callables] Removes a restrictive type inference criterion

loopy/transform/callable.py, test/test_callables.py
Also includes a fix for maintaining argument shapes
Targets #222.
=> test _match_caller_callee_argument_dimension_

loopy/target/c/__init__.py, test/test_callables.py
=> CTarget: support max, min

loopy/kernel/instruction.py, loopy/symbolic.py, loopy/transform/callable.py, loopy/transform/iname.py
=> Acknowledge that Sub-array refs' swept inames to be used inames

loopy/target/c/__init__.py
=> CTarget: Add c prefix to real and imag

doc/conf.py, doc/ref_translation_unit.rst, loopy/kernel/function_interface.py, loopy/preprocess.py, loopy/translation_unit.py, loopy/type_inference.py
=> [callables] InKernelCallable, CallablesInferenceContext: better docs

loopy/kernel/function_interface.py, loopy/library/random123.py
=> [callables] Adds :attr:`InKernelCallable.name`

doc/misc.rst, loopy/kernel/__init__.py, loopy/kernel/creation.py, setup.py, test/test_loopy.py
=> Make LoopKernel a subclass of Taggable

test/test_loopy.py
=> Fix test_kernel_tagging

loopy/check.py, loopy/kernel/creation.py, loopy/kernel/function_interface.py, loopy/kernel/instruction.py, loopy/preprocess.py, loopy/statistics.py, loopy/symbolic.py, loopy/transform/callable.py, loopy/translation_unit.py, loopy/type_inference.py, test/test_callables.py
* deserves a better implementation
Targets #222
=> [callables] Remove support for Calling with keyword args

loopy/translation_unit.py
=> Delete dead find_in_knl_callable_from_identifier, fix sectioning in translation_unit

loopy/codegen/__init__.py
=> [callables] motivate call to diverge_callee_entrypoints

doc/ref_creation.rst, loopy/__init__.py, test/test_einsum.py
=> Add make_einsum

README.rst, asv.conf.json, benchmarks/run_sumpy_kernels.py
=> [callables] Fix benchmarks

benchmarks/run_sumpy_kernels.py
=> [callables] Fix typo

loopy/__init__.py, loopy/kernel/creation.py, loopy/kernel/tools.py, loopy/loop.py, loopy/transform/add_barrier.py, loopy/transform/arithmetic.py, loopy/transform/batch.py, loopy/transform/callable.py, loopy/transform/data.py, loopy/transform/iname.py, loopy/transform/instruction.py, loopy/transform/padding.py, loopy/transform/parameter.py, loopy/transform/subst.py, loopy/translation_unit.py
- Targets #222
- b778215 is the result of `git grep -l iterate_over_kernels_if_given_program | xargs sed -i -e "s/iterate_over_kernels_if_given_program/for_each_kernel/g"`
-  4696cdc improves the docs of for_each_kernel
=> [callables] iterate_over_kernels_if_given_program -> for_each_kernel

loopy/codegen/__init__.py
=> [callables] remove memoize_method from generate_code_v2

doc/ref_call.rst, loopy/kernel/data.py
=> [callables] Clarify the conventions chosen for a valid kernel call site

loopy/check.py
=> [callables] Implements check_sub_array_ref_inames_not_within_or_redn_inames

doc/misc.rst, doc/ref_transform.rst, loopy/__init__.py, loopy/kernel/creation.py, loopy/target/python.py
=> [callables] Purge function manglers

loopy/check.py, loopy/codegen/__init__.py, loopy/codegen/control.py, loopy/codegen/loop.py, loopy/kernel/__init__.py, loopy/kernel/function_interface.py, loopy/schedule/__init__.py, loopy/target/__init__.py, loopy/target/ispc.py, loopy/target/pyopencl.py, test/test_callables.py
Targets #222
- For more context see: https://github.com/inducer/loopy/commit/827348c08e1e896c5313454ee31cde804459dda6
=> [callables] Re-enable check_unused_hw_axes

.github/workflows/ci.yml
=> kcv3 downstream grudge CI: Use appropriate branch

loopy/check.py, loopy/frontend/fortran/translator.py, loopy/symbolic.py, loopy/translation_unit.py
=> [callables] Implements validate_kernel_call_sites

loopy/check.py, loopy/diagnostic.py, loopy/options.py, loopy/symbolic.py, test/test_transform.py
See ce6a6dc for context.
(Some hacky version of this was lying around in my pytato_array_context branch. I decided to upstream this.)
=> Test chunk_iname with integral loop bounds

loopy/frontend/fortran/__init__.py, loopy/frontend/fortran/translator.py, loopy/frontend/fortran/tree.py, loopy/symbolic.py, test/test_fortran.py, test/test_numa_diff.py
Follow-on to #363.
cc @jdsteve2
=> Half-fix Fortran integer division

.test-conda-env-py3.yml, loopy/check.py, loopy/codegen/__init__.py, loopy/diagnostic.py, loopy/frontend/fortran/__init__.py, loopy/frontend/fortran/translator.py, loopy/frontend/fortran/tree.py, loopy/kernel/instruction.py, loopy/options.py, loopy/preprocess.py, loopy/symbolic.py, loopy/target/execution.py, loopy/target/pyopencl.py, loopy/target/pyopencl_execution.py, loopy/transform/callable.py, loopy/transform/fusion.py, loopy/transform/iname.py, loopy/translation_unit.py, loopy/type_inference.py, test/test_fortran.py, test/test_numa_diff.py, test/test_transform.py
Targets #222.
@kaushikcfd Could you take a look at how gross you find f21d518, specifically the bit labeled `HACK`? 
(This won't really merge, I'll simply fast-forward push these commits to #222 once CI passes and you're OK.)
=> Merge main into kcv3-e2

loopy/codegen/__init__.py, loopy/kernel/function_interface.py, loopy/kernel/tools.py, loopy/library/reduction.py, loopy/preprocess.py, loopy/translation_unit.py
=> [callables] Improves unique callable ID generation

loopy/check.py, loopy/kernel/__init__.py, loopy/kernel/function_interface.py, loopy/kernel/instruction.py, loopy/library/reduction.py, loopy/preprocess.py
=> [callables] Uses different sub-classes for ArgExtOpCallable and SegmentOpCallable

loopy/isl_helpers.py, test/test_loopy.py
=> Fix and simplify duplicate axes

loopy/transform/parameter.py, loopy/type_inference.py, test/test_callables.py
=> [callables] Removes dead fixmes or resolves them

loopy/check.py, loopy/kernel/__init__.py, loopy/schedule/__init__.py, loopy/schedule/device_mapping.py, loopy/schedule/tools.py, loopy/statistics.py
=> [callables] Merge with main

loopy/target/c/codegen/expression.py, loopy/target/opencl.py, loopy/target/pyopencl.py, test/test_target.py
=> OpenCLTarget: Handle float condition in the ternary operation

doc/Makefile, doc/conf.py, doc/ref_call.rst, loopy/kernel/function_interface.py
- sphinx pygments theme isn't usable in dark mode:
- misc other fixes
=> minor doc fixes

.github/workflows/ci.yml, doc/tutorial.rst, loopy/statistics.py, setup.cfg
Not done, mostly here to test whether CI will now flag doctest failures again.
x-ref: https://github.com/inducer/ci-support/commit/80a50f3f0ef33aef662c03da0c6e850cb4714d95
=> Fix doctests

loopy/target/c/__init__.py, loopy/target/cuda.py, loopy/transform/data.py, loopy/transform/instruction.py, loopy/transform/subst.py, test/test_transform.py
Continuation of https://gitlab.tiker.net/inducer/loopy/-/merge_requests/363
=> Misc minor bugs

loopy/__init__.py, loopy/check.py, loopy/codegen/__init__.py, loopy/schedule/__init__.py, test/test_callables.py, test/test_loopy.py
=> check_bounds: traverse call-graph to propagate information at a call-site

loopy/transform/privatize.py, test/test_transform.py
Privatization was supported only for loops that had zero as their lower
bound. This commit fixes that by subtracting an offset of the iname's
lower bound expression. An option could have been to consider the new
shape of the temporary to be a function of iname's upper bound rather
than purely size, but that might need to unnecessary
register/stack-space usage.
The attached regression fails on `main`.
=> privatization for loops with non-zero base index

loopy/target/c/__init__.py, loopy/target/c/codegen/expression.py, test/test_target.py, test/testlib.py
=> CFamilyTarget: add support for np.inf, -np.inf

loopy/codegen/instruction.py, test/test_loopy.py
=> Test, fix trace_assignments

doc/tutorial.rst, loopy/target/c/c_execution.py, loopy/target/execution.py, loopy/target/pyopencl_execution.py, test/test_expression.py, test/test_loopy.py, test/test_target.py, test/test_transform.py
I fixed the tests that (likely) will benefit from addressing #450 in a separate commit, in case that helps revert those changes later (if desired).
=> Add check for missing input ArrayArgs

loopy/check.py, test/test_loopy.py
The test included with this patch fails on `main` with the following error message:
```
File "/home/kgk2/projects/pytato_multiprogram/src/loopy/loopy/check.py", line 1332, in check_that_temporaries_are_defined_in_subkernels_where_used                                                               
raise MissingDefinitionError("temporary variable '%s' gets "                                         
loopy.diagnostic.MissingDefinitionError: temporary variable 'tmp' gets used in subkernel 'loopy_kernel_0' and neither it nor its aliases have a definition
```
=> Bugfix: Global temporaries with base storage across gbarrier

doc/ref_other.rst, loopy/__init__.py, loopy/tools.py, test/test_loopy.py
=> Adds a routine to get a LoopKernel reproducer

loopy/type_inference.py
=> Simplify control flow in type inference, fix a possible unassigned variable

loopy/type_inference.py
Before this, `(struct type + scalar type)` would always result in the struct type, which is very incorrect. This restricts that processing to cases where all elements of the struct agree with the scalar type.
=> Fix TypeInferenceMapper.combine for vector types

loopy/statistics.py, test/test_statistics.py
When the global memory stats counter finds a subscript that is a temporary variable, don't assume it shouldn't be counted. If its address space is global, count it. This can occur when the address space of a temporary is set to global (see new test case for example).
It's possible that a similar change should be made in `GlobalMemAccessMapper.map_variable` (?), but I'm keeping this PR's scope narrow... for now.
=> Count temporary subscripts with global address space as globals

loopy/target/pyopencl.py, test/test_expression.py
Adds helpers to allow calling `real` and `imag` with real arguments, not just complex ones, in the `pyopencl` target.
x-ref: inducer/arraycontext#76
=> Fix real and imag with real inputs in pyopencl target

loopy/preprocess.py, test/test_loopy.py
- Closes #427 
- Provided test fails on main
=> Correctly realize reduction guarded by predicates

loopy/kernel/creation.py, loopy/target/c/codegen/expression.py, loopy/target/pyopencl.py
=> Fix some warnings

loopy/__init__.py, loopy/preprocess.py, loopy/tools.py, loopy/transform/buffer.py, test/test_misc.py, test/test_reduction.py
Pretty helpful if costly transforms are triggered from the user land.
=> Adds functionality to memoize the result of a transformation on disk

loopy/kernel/instruction.py, loopy/library/reduction.py, loopy/transform/realize_reduction.py, test/test_reduction.py, test/test_scan.py
This already contains the fix for #533 (in `map_if`), and it already passes non-nested reduction tests. But:
=> Make `realize_reduction` actually recursive

loopy/target/pyopencl.py
Previous PR was for redundant addition by zero. This one fixes the multiplication.
=> Remove redundant multiplication by one

loopy/transform/precompute.py, test/test_transform.py
=> [bugfix]: Precompute over instructions after a gbarrier

loopy/transform/buffer.py, test/test_transform.py
=> Preserve reverse depends for buffer_array's store instructions

loopy/__init__.py, loopy/target/c/__init__.py, requirements.txt, test/test_target.py
=> Adds support for bessel functions supported in glibc

loopy/library/reduction.py, loopy/symbolic.py, loopy/target/opencl.py, loopy/target/pyopencl.py, loopy/translation_unit.py, loopy/type_inference.py, loopy/types.py, test/test_apps.py
Partial fix to https://github.com/inducer/loopy/issues/554
=> Allow abs(int) in opencl

loopy/check.py, loopy/isl_helpers.py, loopy/symbolic.py, loopy/transform/buffer.py, loopy/transform/callable.py, loopy/transform/pack_and_unpack_args.py, loopy/transform/precompute.py, test/test_isl.py, test/test_transform.py
Fixes https://github.com/inducer/loopy/issues/559
=> Fix simplify_using_aff to add non iname deps as unbounded

loopy/tools.py, setup.py
Cf. https://github.com/inducer/pytools/pull/122.
=> Drop `update_for_type` from `LoopyKeyBuilder`

loopy/transform/buffer.py, test/test_transform.py
Provided test fails on `main`.
=> Bugfix: lp.buffer_array's within argument is broken

loopy/kernel/__init__.py, loopy/kernel/creation.py, loopy/schedule/__init__.py, loopy/statistics.py, loopy/target/c/__init__.py, loopy/target/python.py
Alternative to #585.
@kaushikcfd, what do you think?
=> Fix instances of B020: loops that assign iterables

loopy/transform/iname.py, test/test_transform.py
=> make_reduction_inames_unique: preserve metadata

.ci/examples-funcs.sh, .github/workflows/ci.yml, .gitlab-ci.yml, examples/python/find-centers.py
=> Downstream CI: use ci-support, add Gitlab

loopy/target/pyopencl.py
Helps with debugging issues like in #602.
This is ready for review @inducer @kaushikcfd
=> more verbose arg count assert in pyopencl host code

.github/workflows/ci.yml
=> Firedrake CI: update pymbolic

loopy/transform/callable.py, test/test_callables.py
=> [callable.inline]: Support arguments with zero-stride axes

loopy/kernel/data.py, loopy/transform/callable.py
=> Misc. minor fixes

doc/misc.rst, doc/tutorial.rst, examples/fortran/matmul-driver.py, examples/python/find-centers.py, examples/python/global_barrier_removal.py, examples/python/ispc-stream-harness.py, examples/python/rank-one.py, examples/python/sparse.py, examples/python/vector-types.py, loopy/frontend/fortran/translator.py, loopy/target/c/c_execution.py, loopy/target/cuda.py, loopy/target/execution.py, loopy/target/opencl.py, loopy/target/pyopencl.py, loopy/target/pyopencl_execution.py, test/test_apps.py, test/test_callables.py, test/test_diff.py, test/test_domain.py, test/test_expression.py, test/test_loopy.py, test/test_numa_diff.py, test/test_reduction.py, test/test_statistics.py, test/test_target.py, test/test_transform.py
The commits should be fairly self-contained and self-explanatory.
=> Fix some deprecation warnings in tests

loopy/transform/callable.py
=> Avoid mutable update to kernel.inames

loopy/kernel/instruction.py, test/test_callables.py
=> Fix dependency calculation for lp.CInstruction

loopy/symbolic.py, test/test_isl.py
The provided test fails on `main`.
=> qpolynomial_to_expr: Account for rational coefficients

loopy/transform/iname.py, loopy/transform/instruction.py, loopy/transform/subst.py
These changes (along with some changes in loop fusion branch) get me ~50% transform time reduction for the case reported in https://github.com/illinois-ceesd/mirgecom/issues/644.
=> Bag of transformation implementation improvements

loopy/kernel/__init__.py, loopy/transform/iname.py, test/test_loopy.py
=> applied_iname_rewrites:  allow only tuple type

.github/workflows/ci.yml
x-ref: https://github.com/firedrakeproject/firedrake/issues/2514
=> Avoid failing firedrake gtmg tests

loopy/kernel/creation.py, loopy/transform/callable.py, test/test_callables.py
=> Inliner: mark generated start/end-func deps final

loopy/target/cuda.py, loopy/target/opencl.py
Resolves https://github.com/inducer/loopy/issues/660
=> Add symbol mangler to CUDA target

requirements.txt, setup.py
Needed because https://github.com/inducer/pytools/pull/133 is in 2022.1.7
=> Update pytools requirements

loopy/translation_unit.py
Managed to hit this by using `make_function` instead of `make_kernel` and not knowing what I'm doing. Not sure if the suggestion is sound, so let me know!
=> Nicer message for 0 entrypoints

loopy/kernel/array.py
Just added an `expected X but got Y` to it :D
=> Improve message for Array dim mismatch

loopy/kernel/array.py, loopy/kernel/data.py, loopy/target/c/__init__.py, loopy/target/c/c_execution.py, loopy/target/execution.py, loopy/target/pyopencl.py, loopy/target/pyopencl_execution.py, loopy/transform/data.py, loopy/transform/precompute.py
See
1. https://github.com/inducer/loopy/blob/ed6b298cb2bf70a4dd815d26b595107c7616852a/loopy/kernel/array.py#L770-L771
=> Corrects the type of ArrayBase.dtype

test/test_expression.py
=> Work around long compile times for complex fuzzed expressions on gcc 11+

loopy/statistics.py, test/test_statistics.py
=> extend 'within' mechanism to statistics

doc/conf.py
=> Set nitpicky mode in doc

loopy/target/c/__init__.py
(With this change, 100% of tests pass on MacOS M1)
=> fix Bessel function name on MacOS

loopy/expression.py, loopy/target/c/c_execution.py, loopy/target/c/codegen/expression.py, loopy/target/opencl.py, loopy/target/pyopencl_execution.py, loopy/target/python.py, test/test_expression.py, test/test_target.py
`np.bool8` is deprecated in numpy 1.24
=> np.bool8 -> np.bool_

loopy/transform/callable.py, test/test_callables.py
=> Add predicates to no-op instruction

loopy/__init__.py, test/test_loopy.py
=> Fix einsum subscript parsing for specs with spaces

loopy/target/cuda.py, test/test_target.py
=> Do not use OpenCL C types for CUDA target

loopy/statistics.py
=> Do not attempt op counting for CInstructions

loopy/schedule/__init__.py, test/test_loopy.py
=> Avoid introducing dependency record when there are no race variables

loopy/kernel/__init__.py, test/test_apps.py
=> `combine_domains`: Handle inames that occur as parameters other domains 

loopy/codegen/instruction.py, loopy/target/__init__.py, loopy/target/c/__init__.py, loopy/target/python.py, test/test_target.py
and no other instructions with the same predicate
=> Fix NoOpInstrunction with predicate

loopy/kernel/array.py, loopy/kernel/creation.py, loopy/target/c/c_execution.py, loopy/target/execution.py, test/test_einsum.py
=> Support `default_order=auto` in kernel creation

loopy/isl_helpers.py, loopy/symbolic.py, loopy/target/c/codegen/expression.py, test/test_target.py
=> Pass all arguments to CSE constructor

doc/ref_kernel.rst, doc/tutorial.rst, loopy/__init__.py, loopy/kernel/data.py, loopy/target/c/__init__.py, loopy/target/c/codegen/expression.py, loopy/target/cuda.py, loopy/transform/array_buffer_map.py, loopy/transform/data.py, loopy/transform/precompute.py, loopy/types.py, loopy/typing.py, test/test_loopy.py
(If we're honest about it, the whole "type context" thing doesn't make a great deal of sense and should probably abolished.)
=> Various fixes on the way to NCSA WEST

.github/workflows/ci.yml, .gitlab-ci.yml, loopy/kernel/creation.py, loopy/symbolic.py, loopy/transform/array_buffer_map.py, loopy/transform/precompute.py, loopy/typing.py, test/test_transform.py
It's not pretty, but it seems to do the job. @inducer Is this kind of what you had in mind? If yes, I'll hand it off to Mike to do some more stress testing on lassen before we merge (I've only tested at small scales on my laptop so far).
=> Add special case to work around length-1 loop index removal in meshmode array contraction

loopy/target/c/codegen/expression.py, test/test_fortran.py
=> Work around numpy2's changed `repr` for scalars

doc/ref_call.rst, doc/ref_translation_unit.rst, loopy/__init__.py, loopy/codegen/__init__.py, loopy/kernel/function_interface.py, loopy/library/function.py, loopy/schedule/__init__.py, loopy/target/execution.py, loopy/transform/precompute.py, loopy/transform/realize_reduction.py, loopy/translation_unit.py, setup.py
Fixes mypy failures such as [these](https://gitlab.tiker.net/inducer/loopy/-/jobs/685366), needed after https://github.com/inducer/pytools/pull/212.
=> Annotate cache types

loopy/__init__.py
A minor convenience for me, please merge if for thee as well. :smile:
=> Export lp.for_each_kernel

loopy/target/c/__init__.py, loopy/target/c/c_execution.py, loopy/target/pyopencl.py, test/test_expression.py
=> Complex math functions with real-valued arguments

loopy/kernel/data.py, loopy/match.py, loopy/target/execution.py, loopy/transform/iname.py, test/test_transform.py
=> Tag_inames should include all applicable tags when multiple are passed in.

doc/conf.py, doc/tutorial.rst, loopy/check.py, loopy/codegen/__init__.py, loopy/codegen/tools.py, loopy/isl_helpers.py, loopy/kernel/__init__.py, loopy/kernel/array.py, loopy/kernel/data.py, loopy/kernel/instruction.py, loopy/preprocess.py, loopy/statistics.py, loopy/symbolic.py, loopy/target/__init__.py, loopy/target/c/__init__.py, loopy/target/c/c_execution.py, loopy/target/c/codegen/expression.py, loopy/target/execution.py, loopy/target/ispc.py, loopy/target/pyopencl.py, loopy/target/pyopencl_execution.py, loopy/transform/array_buffer_map.py, loopy/transform/data.py, loopy/transform/precompute.py, loopy/transform/realize_reduction.py, loopy/typing.py, pyproject.toml
=> Track renames in pymbolic 2024.2

doc/ref_kernel.rst, loopy/target/c/__init__.py, loopy/target/cuda.py, loopy/target/ispc.py, loopy/target/pyopencl.py, pyproject.toml
=> Annotation for mildly typed cgen

.github/workflows/ci.yml, .gitlab-ci.yml, loopy/options.py, loopy/target/c/__init__.py, loopy/target/opencl.py, loopy/target/pyopencl.py, pyproject.toml
Added some more typing to cgen during the break that caused some errors in loopy. This preemptively fixes them :D
=> mypy: fix errors from stricter cgen typing

loopy/transform/iname.py
Source/analogous to: https://github.com/illinois-ceesd/loopy/pull/5/files
cc @matthiasdiener
=> _ReductionInameUniquifier: speed up get_cache_key

loopy/expression.py, loopy/transform/padding.py, test/test_target.py
=> Allow, test vectorization of ternaries

.github/workflows/ci.yml, loopy/transform/iname.py
=> Fix typo: establishing

loopy/auto_test.py, loopy/check.py, loopy/expression.py, loopy/kernel/array.py, loopy/kernel/creation.py, loopy/library/function.py, loopy/library/reduction.py, loopy/symbolic.py, loopy/target/c/codegen/expression.py, loopy/target/ispc.py, loopy/transform/array_buffer_map.py, loopy/transform/instruction.py, loopy/transform/padding.py
=> Pymbolic follow 2025 07
